# Generated by Django 3.2.7 on 2021-10-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_answersheet_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='remaining_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_time',
            field=models.DurationField(),
        ),
    ]
