# Generated by Django 3.2.7 on 2021-10-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211004_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.TextField(),
        ),
    ]
